config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#index'
  # root 'orders#new'

  get 'user/new'
  get 'user/create'
  get 'user/show'



  resources :attendance
  resources :event

  get 'static_pages/secret'
  devise_for :users
 
  root 'orders#new'
  resources :orders, only: [:new, :create]
 
  #new, #create, #show, #index, #edit, #update, #destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord


    has_many :attendances
    has_many :users, through: :attendances
    #belongs_to :user

    #TODO : validateur !!
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances

    # validates :title, presence: true
    # validates :description, presence: true
    # validates :start_date, presence: true
    # validates :end_date, presence: true
    # validates :duration, presence: true
    # validates :price, presence: true
    # validates :location, presence: true




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     after_create :welcome_send
    
    has_many :attendances
    has_many :events, through: :attendances
    validates :email, presence: true
   
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @events = Event.all
    @users = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    # @event = Event.create(title: params[:title], description: params[:description], price: params[:price],  location: params[:location], user_id: current_user.id)

    @event = Event.new(title: params[:title], description: params[:description], price: params[:price],  location: params[:location])

      if @event.save
        puts "#" * 30
        redirect_to root_path
        # flash
        # render "/event/index_sucess"
    else
      puts "*" * 60
      render :new
        # render "/event/new_error"
    end
  end

  # def edit
  #   @event = Event.find(params[:id])
  # end

  # def update
  #   @gossip = Gossip.find(params[:id])
  #   if @gossip.update(post_params)
  #       redirect_to gossip_index_path
  #   else
  #       render '/event/edit_error'
  #   end
  # end

  # def destroy
  # end
end

app/controllers/events_controller.rb
class EventController < ApplicationController
  def index
    @events = Event.all
    @users = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    # @event = Event.create(title: params[:title], description: params[:description], price: params[:price],  location: params[:location], user_id: current_user.id)

    @event = Event.new(title: params[:title], description: params[:description], price: params[:price],  location: params[:location])

      if @event.save
        # puts "#" * 30
        redirect_to root_path
        # flash
        # render "/event/index_sucess"
    else
      puts "*" * 60
      render :new
        # render "/event/new_error"
    end
  end

  # def edit
  #   @event = Event.find(params[:id])
  # end

  # def update
  #   @gossip = Gossip.find(params[:id])
  #   if @gossip.update(post_params)
  #       redirect_to gossip_index_path
  #   else
  #       render '/event/edit_error'
  #   end
  # end

  # def destroy
  # end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @user = User.first
    @event = Event.first
    @amount = @event.price

  end

  def create
      # Before the rescue, at the beginning of the method
      @stripe_amount = 500
      begin 
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
        })  

      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @stripe_amount,
        description: "Achat d'un produit",
        currency: 'eur',
        })

      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_order_path
      end
      # After the rescue, if the payment succeeded
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
  
    @event = Event.new(email: params[:email])  
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendance/create.html.erb
<h1>Attendance#create</h1>
<p>Find me in app/views/attendance/create.html.erb</p>

app/views/attendance/destroy.html.erb
<h1>Attendance#destroy</h1>
<p>Find me in app/views/attendance/destroy.html.erb</p>

app/views/attendance/edit.html.erb
<h1>Attendance#edit</h1>
<p>Find me in app/views/attendance/edit.html.erb</p>

app/views/attendance/index.html.erb
<h1>Attendance#index</h1>
<p>Find me in app/views/attendance/index.html.erb</p>

app/views/attendance/new.html.erb
<h1>Attendance#new</h1>
<p>Find me in app/views/attendance/new.html.erb</p>

app/views/attendance/show.html.erb
<h1>Attendance#show</h1>
<p>Find me in app/views/attendance/show.html.erb</p>

app/views/attendance/update.html.erb
<h1>Attendance#update</h1>
<p>Find me in app/views/attendance/update.html.erb</p>

app/views/event/new.html.erb
<div class="container text-center" >
<br>
<h2>Create a event </h2>
<%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <%= label_tag 'Title' %><br>
    <%= text_field_tag(:title) %>
    <br /> <br />

    <%= label_tag 'Description' %><br>
    <%= text_field_tag(:description) %>
    <br /> <br />

  

    <%= label_tag 'Price' %><br>
    <%= text_field_tag(:price) %>
    <br /> <br />

    <%= label_tag 'Location' %><br>
    <%= text_field_tag(:location) %>
    <br /> <br />

    <%= label_tag 'Duration' %><br>
    <%= text_field_tag(:duration) %>
    <br /> <br />

  <%=submit_tag "Create Event" %>

<% end %>
  </div>

app/views/events/_old_new.html.erb
<div class="container">
<div class="jumbotron">
<h1 class='title'>cree ton event</h1>

 


<div class style="background-color:powderblue;">
<% if @event.errors.any? %>
  <p>⚠️ Nous n'avons pas réussi à créer un event pour la raison suivante :</p><ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>




formulaire_tag
<%= form_tag url_for(action: 'create'), method: "post" do %>
      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @event.title %>
      <br /> <br />

      <%= label_tag 'description' %>
      <%= text_area_tag 'description', @event.description %>
      <br /> <br />

      <%= label_tag 'location' %>
      <%= text_field_tag 'location', @event.location %>
    
      <%= label_tag 'price' %>
      <%= text_field_tag 'price', @event.price %>


      <br /> <br />

      <%= submit_tag "Create Event" %>
 <% end %>



</div>
</div>

app/views/events/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Event#edit</h1>
<p>Find me in app/views/event/edit.html.erb</p>

app/views/events/edit_error.html.erb
aye

app/views/events/index.html.erb
<h1>Liste des evenements </h1>
<p>Find me in app/views/event/index.html.erb</p>

<div class="index_page">
    <%@events.each do |event|%>
       
        <h3 class="title" style="text-decoration:none;"> <%=event.title%></h3>
          
        </a>
    <%end%>
</div>

app/views/events/index_succes.html.erb
bravo

app/views/events/new.html.erb
  <%= form_with model: @event, local: true, html: { class: "form-signin mt-3" } do |f| %>

      <h1 class="h3 mb-3 font-weight-normal text-center">Create Event</h1>
      <p>Start Date :<br/><%= f.datetime_select :start_date, class: "form-control" %></p>
      <p>Duration :<br/> <%= f.number_field :duration, class: "form-control" %></p>
      <p>Event Title :<br/><%= f.text_field :title, class: "form-control"%></p>
      <p>Inscription Fees :<br/><%= f.number_field :price, class: "form-control" %></p>
      <p>Event Location :<br/><%= f.text_field :location, class: "form-control" %></p>
      <p>Event Description :<br/><%= f.text_field :description, class: "form-control"%></p>
      <div class="actions mt-5">
        <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
      </div>
      <% end %>

app/views/events/new_error.html.erb
<p>vous devez etre connecter pour creer un event</p>

app/views/events/show.html.erb
<h1>Event#show</h1>
<p>Find me in app/views/event/show.html.erb</p>

app/views/events/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand title" href="/">eventBrit</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
       <div class="navbar-nav">
         <a class="nav-item nav-link active" href=<%=root_path%>> Acceuil  <span class="sr-only">(current)</span></a>
      
        <a class="nav-item nav-link active" href=<%=event_new_path%>> creer un evenement   <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link active" href=<%=event_new_path%>> s'inscrire   <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href=<%=new_user_session_path%>> se connecter  <span class="sr-only">(current)</span></a>
       </div>
      </div>
     
<!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Dropdown link
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
      </div>
    </li>



    </nav>



  </head>

  <body>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>






    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href=<%=root_path%>> Eventbrite </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href=<%=user_new_path%>> s'inscrire  </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href=<%=event_new_path%>> creer un evenement</a>  
    </li>



    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        connexion
      </a>
      <div class="dropdown-menu">
         
       
<ul>
  <% if user_signed_in? %>
    <li>
     <%= button_to( "Sign out/ Se deconneter", destroy_user_session_path,  method: :delete) %>
    
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in/ Se connecter", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up/ s'inscrire", new_user_registration_path %>
    </li>

  <% end %>
</ul>

      </div>
    </li>


  <li class="nav-item">
    <% if user_signed_in? %>
     <a class="navbar-brand" >   <%= current_user.email %> 
     <% end %>
      </a>
    </li>


  </ul>

</nav>
<br>
  


</body>
</html>


  </head>

  <body>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>






    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<%= form_tag orders_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  
  <label class="amount">
    <span>Amount: $5.00</span>
  </label>


</article><script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount="500"
    data-locale="auto">
</script>
<% end %>

app/views/static_pages/index.html.erb
<html>
  <head>
    <title>Buy cool new product</title>
  </head>
  <body>
    <form action="/create-checkout-session" method="POST">
      <button type="submit">Checkout</button>
    </form>


<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

 <a class="btn btn-lg my-btn" href=<%=event_index_path%> role="button">afficher les evenements </a>
    </div>
  </div>
</div>





  </body>
</html>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/old_create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/old_new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/old_show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>